# Generated by Django 5.1.1 on 2024-10-20 13:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=100, verbose_name="Наименование категории")),
                ("description", models.TextField(verbose_name="Описание")),
            ],
            options={
                "db_table": "categories",
            },
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=100, verbose_name="Наименование продукта")),
                ("description", models.CharField(max_length=1000, verbose_name="Описание")),
                ("image", models.ImageField(upload_to="photos/")),
                ("category", models.CharField(max_length=100, verbose_name="Категория")),
                ("price", models.IntegerField()),
                ("created_at", models.DateField(auto_now_add=True)),
                ("updated_at", models.DateField(auto_now=True)),
                (
                    "category_product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING, related_name="products", to="catalog.category"
                    ),
                ),
            ],
            options={
                "db_table": "products",
                "ordering": ["category"],
            },
        ),
    ]
