# Generated by Django 5.1.1 on 2024-10-20 15:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="category_product",
        ),
        migrations.AlterField(
            model_name="product",
            name="category",
            field=models.ForeignKey(
                max_length=100,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="products",
                to="catalog.category",
                verbose_name="Категория",
            ),
        ),
    ]
