# Generated by Django 5.1.1 on 2024-10-20 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0003_alter_product_price"),
    ]

    operations = [
        migrations.CreateModel(
            name="Contact",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("phone_number", models.CharField(max_length=12)),
                ("email", models.EmailField(max_length=254)),
                ("address", models.TextField()),
            ],
            options={
                "db_table": "contacts",
            },
        ),
    ]
